# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#
#[main.params]
#icon = "home"
#newtab = true

# https://tabler.io/icons
[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/jemgunay"
weight = 1

[social.params]
icon = "brand-github"

[[social]]
identifier = "linkedin"
name = "Linkedin"
url = "https://www.linkedin.com/in/jem-gunay/"
weight = 2

[social.params]
icon = "brand-linkedin"

[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://www.instagram.com/tinker_turk/"
weight = 3

[social.params]
icon = "brand-instagram"